trigger:
- master


stages:
- stage: sonar
  jobs:
  - job: sonar
    displayName: 'sonar'
    steps:
      - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          SonarCloud: patdie421
          organization: 'mea-edmous-lite'
          projectKey: 'mea-edomus-lite'
          projectName: 'mea-edomus-lite'

- stage: etape1
  jobs:
  - job: ubuntu
    displayName: 'ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: sudo apt update
    - script: sudo apt install libcurl4-openssl-dev libpython-dev libpython2.7-dev python-dev
    - script: make -f Makefile.ubuntu clean-all ; make -f Makefile.ubuntu

  - job: macosx
    displayName: 'macosx'
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: make -f Makefile.macosx clean-all ; make -f Makefile.macosx
    - publish: package/ea-edomus.tar.pkg.bz2

- stage: etape2
  jobs:
  - job: jenkins
    displayName: 'jenkins'
    steps:
      - task: JenkinsQueueJob@2
        inputs:
          serverEndpoint: 'jenkins'
          jobName: 'mea-edomus-lite'
          captureConsole: true
          capturePipeline: true
          isParameterizedJob: false
