# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: ubuntu
  displayName: 'ubuntu'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt update
  - script: sudo apt install libcurl4-openssl-dev libpython-dev libpython2.7-dev python-dev
  - script: make -f Makefile.ubuntu

jobs:
- job: macosx
  displayName: 'macosx'
  pool:
    vmImage: 'ubuntu-macosx'
  steps:
  - script: make -f Makefile.macosx
