#!/bin/sh

### BEGIN INIT INFO
# Provides:        xplhub
# Required-Start:  $network
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start xplhub daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

MEAEDOMUS_BASEPATH="<BASEPATH>"

#DAEMON="$MEAEDOMUS_BASEPATH/bin/xPL_Hub_static"
DAEMON="$MEAEDOMUS_BASEPATH/bin/xPL_Hub"

XPLHUB_OPT="<INTERFACE>"

test -x $DAEMON || exit 5

#if [ -r /etc/default/xPL_Hub ]; then
#	. /etc/default/xPL_Hub
#fi

RUNASUSER=mea-edomus
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true

case $1 in
	start)
		log_daemon_msg "Starting xPL_Hub" "xPL_Hub"
		if [ -z "$UGID" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi
  		start-stop-daemon --exec $DAEMON --chuid $RUNASUSER --start --startas $DAEMON -- $XPLHUB_OPT
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping xPL_Hub" "xPL_Hub"
                pkill xPL_Hub
		status=$?
		log_end_msg $status
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	status)
		status_of_proc $DAEMON "xPL_Hub"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
