// Create a custom Cloud9 build system - similar to the Sublime build system
// For more information see http://docs.aws.amazon.com/console/cloud9/create-builder-runner
{
    "cmd" : [ "$project_path/mea-edomus-lite/c9/build.sh", "file=$file", "project_path=$project_path", "file_name=$file_name", "args=$args"  ],
    "env" : {},
    "info" : "Building",
    "selector": "source.ext"
}
